### ISSUE TITLE
SecurityTrait

### ISSUE THREAD

**Issue by juizmill** [marcojanssen/silex-routing-service-provider#12]
Do you have any example of using **_ Silex\Route\SecurityTrait _**?

http://silex.sensiolabs.org/doc/providers/security.html#traits

**Comment by marcojanssen** [comment]
Did a quick read through the documentation, but don't think it would work with the current setup. Feel free to add the option though

**Comment by juizmill** [comment]
Ok I'll check

**Comment by youssman** [comment]
I think we can close this issue. It was fixed in the v1.6.0.
