### ISSUE TITLE
Adding before/after middleware error

### ISSUE THREAD

**Issue by youssman** [marcojanssen/silex-routing-service-provider#16]
Hello,

I'm trying to add a before middleware to my route but I got this error: 

`Catchable fatal error: Object of class app\utils\middlewares\Authentication could not be converted to string in vendor/marcojanssen/silex-routing-service-provider/src/MJanssen/Provider/RoutingServiceProvider.php on line 292`

Here is my code:

```php
    'config.routes' => array(
        array(
            'pattern' => '%baseUrl%/api/users/{id}',
            'controller' => 'app\controllers\IndexController::getAction',
            'method' => array(
                'get'
            ),
            'value' => array(
                'namespace' => 'core',
                'entity' => 'users'
            ),
            'before' => array(new \app\utils\middlewares\Authentication())
        ),
    )
```
For now the `Authentication` class is the same as the class in the readme.

Am I doing something wrong ? Any help would be great.

Thanks

**Comment by youssman** [comment]
This way worked for me:
```php
    'config.routes' => array(
        array(
            'pattern' => '%baseUrl%/api/users/{id}',
            'controller' => 'app\controllers\IndexController::getAction',
            'method' => array(
                'get'
            ),
            'value' => array(
                'namespace' => 'core',
                'entity' => 'users'
            ),
            'before' => function () {
                return new \app\utils\middlewares\Authentication();
            }
        ),
    )
```
The readme needs to be updated ?

**Comment by youssman** [comment]
I think the problem comes from the function `isClosure` here:
```php
protected function isClosure($param)
{
    return is_object($param) && ($param instanceof \Closure);
}
```
The function checks if the parameter is an instance of `Closure`, which is not.

Based on this [SO](http://stackoverflow.com/questions/2835627/php-is-function-to-determine-if-a-variable-is-a-function) thread, the use of `instanceof \Closure` let us check for anonymous functions only while `is_callable` let us verify that the parameter can be called as a function.

Changing the function above like bellow makes the examples in the Readme works:
```php
protected function isClosure($param)
{
    return is_object($param) && is_callable($param);
}
```

If you agree with me I can submit a PR.

Thanks

**Comment by marcojanssen** [comment]
Thanks for reporting and fixing it, merged your PR

**Comment by youssman** [comment]
Thanks !
