### ISSUE TITLE
Support for controller bind method

### ISSUE THREAD

**Issue by ooXei1sh** [marcojanssen/silex-routing-service-provider#4]
Hi, very useful service provider, thank you.

I was trying to add the controller "bind" method in the "routes.php" config because I wanted to use "Silex\Provider\UrlGeneratorServiceProvider" and noticed it is not currently supported. I was able to add the following at the bottom of the "addRouteByMethod" method to get it working:

    if(isset($route['bind'])) {
        $controller->bind($route['bind']);
    }

**Comment by marcojanssen** [comment]
@ooXei1sh Hi

Looking into the pull request from @samir-plusb somehow i missed your entire issue (notification was turned off apparently) sorry for that!

**Comment by marcojanssen** [comment]
@ooXei1sh @samir-plusb Just released samir-plusb's addition, now available in 1.3.0
