### ISSUE TITLE
Object injection into the constructor

### ISSUE THREAD

**Issue by AchrafSoltani** [marcojanssen/silex-routing-service-provider#6]
Hello,

I was wondering if there is a possibility to inject the Request and Application objects directly into the __construct() instead of catching them as method params ?

**Comment by marcojanssen** [comment]
Not really, that would break the entire way how the provider works in combination with pimple

**Comment by AchrafSoltani** [comment]
well i ended up doing this https://github.com/AchrafSoltani/RoutingServiceProvider
